# Generated by Django 3.1 on 2020-08-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
