# Generated by Django 3.1 on 2020-08-12 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_auto_20200812_0958"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "endereco",
                    models.CharField(max_length=200, verbose_name="Endereço"),
                ),
                (
                    "feito",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Feito em"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "descricao",
                    models.CharField(max_length=300, verbose_name="Descrição"),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="PedidoProduto",
            fields=[
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantidade",
                    models.PositiveIntegerField(verbose_name="Quantidade"),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.pedido",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.produto",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
